name: Test and Deploy Simple API

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v5
        with:
          java-version: '21'
          distribution: 'zulu'
          cache: maven
      - name: Test with Maven
        run: mvn test
  build:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v5
        with:
          java-version: '21'
          distribution: 'zulu'
          cache: maven
      - name: Build with Maven
        run: mvn package -DskipTests
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: simple-api
          path: '${{ github.workspace }}/target/*.jar'
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v5
        with:
          name: simple-api
      - name: Deploy to OCI Registry
        run: |
          echo "Deploying to OCI Registry..."
          ls -la